import {
  AUDIBLE_OPTIONS,
  FEEDBACK_VALUES,
  VISIBLE_OPTIONS,
} from "./formValues";

const DEFAULT_VALUES = {
  DEVICE_NAME: "",
  TIMEOUT: 60,
  FEEDBACK: FEEDBACK_VALUES.AUDIBLE,
  AUDIBLE_FEEDBACK: AUDIBLE_OPTIONS.BEEP,
  VISIBLE_FEEDBACK: VISIBLE_OPTIONS.GREEN,
};

export default DEFAULT_VALUES;
