const FEEDBACK_VALUES = {
  AUDIBLE: "audible",
  VISIBLE: "visible",
};

const FEEDBACK_AUDIBLE = {
  BEEP: 0,
  BUUP_BUUP: 1,
  BEEP_BUUP: 2,
  BEEP_BEEP: 3,
};

const FEEDBACK_VISIBLE = {
  GREEN: 0,
  RED: 1,
  BLUE: 2,
};

export { FEEDBACK_VALUES, FEEDBACK_AUDIBLE, FEEDBACK_VISIBLE };
